@host = http://localhost:8080

###

# Retrieve all users
GET {{host}}/users
Content-Type: application/json

###

# Login User

POST {{host}}/login
Content-Type: application/json

{
  "email": "hixy@gmail.com",
  "password": "HixyIs90!"
}

###

POST {{host}}/users/662c056946d9ce9fa8d7765f/favourites/mounts
Content-Type: application/json

{
  "userId": "662c056946d9ce9fa8d7765f",
  "mountId": "2342"
}

###

