@host = http://localhost:8080

###

# Retrieve all users
GET {{host}}/users
Content-Type: application/json

###

# Login User

POST {{host}}/login
Content-Type: application/json

{
  "email": "hixy@gmail.com",
  "password": "HixyIs90!"
}
